### ISSUE TITLE
Consider support for implicit command locations (relative to toc tree)

### ISSUE THREAD

**Issue by isedwards** [open-climate/copa#4]
The first versions of `copa` require the full path of the command's script to be specified (relative to the `conf` directory). Conside adding support for paths that are calculated relative to their position in the `toc.yml` tree. E.g. if nested beneath install, relative, app-stack then these sub-directories will be added automatically if not specified.

Or do we prefer to force users to be explicit?

```
version: "0.1.1"

commands:
  - install:
      - absolute:
          - app: install/absolute/app.yml
          - app-stack:
              app1: install/absolute/app-stack/app1.yml
              app2: install/absolute/app-stack/app2.py
          - copa: copa.example
      - relative:
          - app: app.yml
          - app-stack:
              - app1  # assumes install/absolute/app-stack/app1.yml
              - app2: app2.py
          - copa: copa.example
  - default  # assumes default.yml

```
